### ISSUE TITLE
Mask URL

### ISSUE THREAD

**Issue by ambikaroos** [ambikaroos/CraftDB#16]
So that it remains "craftdb.org" and not "http://nspaceit.com/" which might confuse our very non-internety users

**Comment by payamazadi** [comment]
Whoops! fixed.

**Comment by ambikaroos** [comment]
Thanks! It still shows up as nspaceit.com for the pages that aren't the homepage, though. So, http://nspaceit.com/authors/.  Internet's too slow to attach a screenshot at the moment!

**Comment by payamazadi** [comment]
I cannot replicate this..
